# Generated by Django 5.2.8 on 2025-11-11 01:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_creado_en_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('customer_address', models.CharField(max_length=255)),
                ('customer_lat', models.FloatField()),
                ('customer_lng', models.FloatField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duration_min', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_distance_km', models.FloatField(default=10)),
                ('base_cost', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=8)),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='sin nombre', max_length=100),
        ),
    ]
